"""Finds mutable pins in GitHub Actions config and replaces with immutable commit SHAs.

This is a security best practice that protects against supply chain attacks.

The immutable hashpins generated by this tool include version comments which are
**Dependabot-compatible**.

E.g.:

❌ Mutable pins are a bad practice (you might get pwned!):

```yaml
jobs:
  my-job:
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
```

✅ This tool will convert them to immutable pins:

```yaml
jobs:
  my-job:
    steps:
      - name: "Checkout"
        uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5"  # v4
```
"""
