name: "Enforce PR label"

on:
  pull_request:
    types:
      - "labeled"
      - "unlabeled"
      - "opened"
      - "edited"
      - "synchronize"

jobs:
  enforce-label:
    runs-on: "ubuntu-latest"
    permissions:
      pull-requests: "write"
    steps:
      - name: "enforce-triage-label"
        uses: "jupyterlab/maintainer-tools/.github/actions/enforce-label@0a066382a883380c76bea01d21f1fe73512a8797"  # v1
