name: "Typecheck"

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"


concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: "true"


jobs:
  mypy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install the latest version of uv"
        uses: "astral-sh/setup-uv@v7"

      - name: "Install dependencies"
        run: "uv sync --group test"

      - name: "Run mypy"
        run: "uv run mypy"
